
package pe.gob.pj.cotejows.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "us_cotejoSoap", targetNamespace = "http://tempurl.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsCotejoSoap {


    /**
     * 
     * @param psNom1
     * @param trama
     * @param psNom2
     * @param psNom3
     * @param psMaterno
     * @param psPaterno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "f_criterio_busq_minedu", action = "http://tempurl.org/f_criterio_busq_minedu")
    @WebResult(name = "f_criterio_busq_mineduResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "f_criterio_busq_minedu", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusqMinedu")
    @ResponseWrapper(localName = "f_criterio_busq_mineduResponse", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusqMineduResponse")
    public String fCriterioBusqMinedu(
        @WebParam(name = "ps_paterno", targetNamespace = "http://tempurl.org")
        String psPaterno,
        @WebParam(name = "ps_materno", targetNamespace = "http://tempurl.org")
        String psMaterno,
        @WebParam(name = "ps_nom1", targetNamespace = "http://tempurl.org")
        String psNom1,
        @WebParam(name = "ps_nom2", targetNamespace = "http://tempurl.org")
        String psNom2,
        @WebParam(name = "ps_nom3", targetNamespace = "http://tempurl.org")
        String psNom3,
        @WebParam(name = "ps_aud_dni", targetNamespace = "http://tempurl.org")
        String psAudDni,        
        @WebParam(name = "trama", targetNamespace = "http://tempurl.org")
        String trama);
    /**
     * 
     * @param psNom1
     * @param trama
     * @param psNom2
     * @param psNom3
     * @param psMaterno
     * @param psPaterno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "f_criterio_busq", action = "http://tempurl.org/f_criterio_busq")
    @WebResult(name = "f_criterio_busqResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "f_criterio_busq", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusq")
    @ResponseWrapper(localName = "f_criterio_busqResponse", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusqResponse")
    public String fCriterioBusq(
        @WebParam(name = "ps_paterno", targetNamespace = "http://tempurl.org")
        String psPaterno,
        @WebParam(name = "ps_materno", targetNamespace = "http://tempurl.org")
        String psMaterno,
        @WebParam(name = "ps_nom1", targetNamespace = "http://tempurl.org")
        String psNom1,
        @WebParam(name = "ps_nom2", targetNamespace = "http://tempurl.org")
        String psNom2,
        @WebParam(name = "ps_nom3", targetNamespace = "http://tempurl.org")
        String psNom3,
        @WebParam(name = "ps_aud_dni", targetNamespace = "http://tempurl.org")
        String psAudDni,        
        @WebParam(name = "trama", targetNamespace = "http://tempurl.org")
        String trama);

    /**
     * 
     * @param psNom1
     * @param trama
     * @param psNom2
     * @param psNom3
     * @param psMaterno
     * @param psPaterno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "f_criterio_busq_jur", action = "http://tempurl.org/f_criterio_busq_jur")
    @WebResult(name = "f_criterio_busq_jurResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "f_criterio_busq_jur", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusqJur")
    @ResponseWrapper(localName = "f_criterio_busq_jurResponse", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusqJurResponse")
    public String fCriterioBusqJur(
        @WebParam(name = "ps_paterno", targetNamespace = "http://tempurl.org")
        String psPaterno,
        @WebParam(name = "ps_materno", targetNamespace = "http://tempurl.org")
        String psMaterno,
        @WebParam(name = "ps_nom1", targetNamespace = "http://tempurl.org")
        String psNom1,
        @WebParam(name = "ps_nom2", targetNamespace = "http://tempurl.org")
        String psNom2,
        @WebParam(name = "ps_nom3", targetNamespace = "http://tempurl.org")
        String psNom3,
        @WebParam(name = "ps_aud_dni", targetNamespace = "http://tempurl.org")
        String psAudDni,        
        @WebParam(name = "trama", targetNamespace = "http://tempurl.org")
        String trama);

    /**
     * 
     * @param psNom1
     * @param trama
     * @param psNom2
     * @param psNom3
     * @param psMaterno
     * @param psPaterno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "f_criterio_busq_suc", action = "http://tempurl.org/f_criterio_busq_suc")
    @WebResult(name = "f_criterio_busq_sucResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "f_criterio_busq_suc", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusqSuc")
    @ResponseWrapper(localName = "f_criterio_busq_sucResponse", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusqSucResponse")
    public String fCriterioBusqSuc(
        @WebParam(name = "ps_paterno", targetNamespace = "http://tempurl.org")
        String psPaterno,
        @WebParam(name = "ps_materno", targetNamespace = "http://tempurl.org")
        String psMaterno,
        @WebParam(name = "ps_nom1", targetNamespace = "http://tempurl.org")
        String psNom1,
        @WebParam(name = "ps_nom2", targetNamespace = "http://tempurl.org")
        String psNom2,
        @WebParam(name = "ps_nom3", targetNamespace = "http://tempurl.org")
        String psNom3,
        @WebParam(name = "ps_aud_dni", targetNamespace = "http://tempurl.org")
        String psAudDni,        
        @WebParam(name = "trama", targetNamespace = "http://tempurl.org")
        String trama);

    /**
     * 
     * @param psNom1
     * @param psNom2
     * @param psAudPc
     * @param psAudCodUsuario
     * @param psNom3
     * @param psMaterno
     * @param psAudIp
     * @param psAudDni
     * @param piAudCodEntidad
     * @param psPaterno
     * @param psAudMcaddr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "f_criterio_busq_jne", action = "http://tempurl.org/f_criterio_busq_jne")
    @WebResult(name = "f_criterio_busq_jneResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "f_criterio_busq_jne", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusqJne")
    @ResponseWrapper(localName = "f_criterio_busq_jneResponse", targetNamespace = "http://tempurl.org", className = "pe.gob.pj.cotejows.ws.FCriterioBusqJneResponse")
    public String fCriterioBusqJne(
        @WebParam(name = "ps_paterno", targetNamespace = "http://tempurl.org")
        String psPaterno,
        @WebParam(name = "ps_materno", targetNamespace = "http://tempurl.org")
        String psMaterno,
        @WebParam(name = "ps_nom1", targetNamespace = "http://tempurl.org")
        String psNom1,
        @WebParam(name = "ps_nom2", targetNamespace = "http://tempurl.org")
        String psNom2,
        @WebParam(name = "ps_nom3", targetNamespace = "http://tempurl.org")
        String psNom3,
        @WebParam(name = "ps_aud_dni", targetNamespace = "http://tempurl.org")
        String psAudDni,
        @WebParam(name = "ps_aud_pc", targetNamespace = "http://tempurl.org")
        String psAudPc,
        @WebParam(name = "ps_aud_ip", targetNamespace = "http://tempurl.org")
        String psAudIp,
        @WebParam(name = "ps_aud_cod_usuario", targetNamespace = "http://tempurl.org")
        String psAudCodUsuario,
        @WebParam(name = "ps_aud_mcaddr", targetNamespace = "http://tempurl.org")
        String psAudMcaddr,
        @WebParam(name = "pi_aud_cod_entidad", targetNamespace = "http://tempurl.org")
        short piAudCodEntidad);

}
